language: python
python:
  - "2.7"
  - "3.5"

env:
  - DJANGO_SPEC=Django~=1.8.0
  - DJANGO_SPEC=Django~=1.9.0
  - DJANGO_SPEC=git+https://github.com/django/django.git

install:
  - pip install --use-mirrors $DJANGO_SPEC
  - python setup.py install

script:
  - python setup.py test
