language: python
python:
  - "2.7"
  - "3.4"

env:
  - DJANGO_SPEC=Django==1.6.10
  - DJANGO_SPEC=Django==1.7.5
  - DJANGO_SPEC=git+https://github.com/django/django.git

install:
  - pip install --use-mirrors $DJANGO_SPEC
  - python setup.py install

script:
  - python setup.py test
