language: python
python:
  - "2.7"
  - "3.4"

env:
  - DJANGO_SPEC=Django==1.5.10
  - DJANGO_SPEC=Django==1.6.7
  - DJANGO_SPEC=Django==1.7
  - DJANGO_SPEC=https://github.com/django/django/zipball/master\#egg\Django

install:
  - pip install --use-mirrors $DJANGO_SPEC
  - python setup.py install

script:
  - python setup.py test
